apiVersion: v1
kind: LimitRange
metadata:
  name: mood-diary-limits
  namespace: ai-mood-diary
spec:
  limits:
    - default:
        cpu: "200m"
        memory: 512Mi
      defaultRequest:
        cpu: "50m"
        memory: 128Mi
      max:
        cpu: "1"
        memory: 2Gi
      min:
        cpu: "10m"
        memory: 32Mi
      type: Container