apiVersion: v1
kind: ConfigMap
metadata:
  name: mood-diary-config
  namespace: ai-mood-diary
data:
  DB_HOST: 192.168.100.130
  DB_PORT: "3306"
  DB_USER: bookadmin
  DB_NAME: ai_mood_diary
  JWT_SECRET_KEY: ai-mood-diary-secret-key-2024
  ARK_API_BASE: https://ark.cn-beijing.volces.com/api/coding
  ARK_MODEL: arkmind-v2