apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mood-diary-ingress
  namespace: ai-mood-diary
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: mood-diary-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mood-diary-frontend
                port:
                  number: 80